#!/usr/bin/env python
from socket import *
import sys,os
import struct

if len(sys.argv) != 3:
	print("Error Input")
	quit()

pl_size = 500;
window_size_max = 10;
tout = sys.argv[1]
file_name = sys.argv[2]


ss = socket(AF_INET, SOCK_DGRAM)
tmp = open('channelInfo','rb')
tmpw = tmp.read()
tmpw = tmpw.split()
serverName = tmpw[0]
serverPort = int(tmpw[1])
#print(serverName)
#print(serverPort)
tmp.close()
addr = (serverName,serverPort)


#rs = socket(AF_INET, SOCK_DGRAM)

ss.settimeout(int(tout)/1000)

s = 0;  #seq #
f = open(file_name,'rb')

bfr = []

message = f.read(pl_size)
while (message):
	#########Packet Type########
	pt = 0
	pt = struct.pack("!I", pt)
	#########Packet Length######
	pl = pl_size + 12
	pl = struct.pack("!I", pl)
	#########Sequence Number####
	sn = s
	sn = struct.pack("!I", sn)

	imessage = pt + pl + sn + message
	bfr.append(imessage)
	message = f.read(pl_size)
	s = s + 1

##########EOT##########
pt = struct.pack("!I", 2)
pl = struct.pack("!I", 12)
sn = struct.pack("!I", s)
message = pt + pl + sn
bfr.append(message)
f.close()
#########END BUFFERING AND READY TO SEND!

window_size = 0
expectackseqnum = 0
send_base = 0
s = s - 1

while (expectackseqnum <= s):
	if (window_size >= window_size_max) or (send_base > s):
		try:
			data,add = ss.recvfrom(512)
			pt = struct.unpack("!I",data[0:4])
			pl = struct.unpack("!I",data[4:8])
			sn = struct.unpack("!I",data[8:12])
			print("PKT RECV ACK 12 " + str(sn[0]))
			if (sn[0] == expectackseqnum):
				expectackseqnum = expectackseqnum + 1
				window_size = send_base - expectackseqnum
			if (sn[0] > expectackseqnum):
				send_base = expectackseqnum
				window_size = send_base - expectackseqnum
		except timeout:
			send_base = expectackseqnum
			window_size = send_base - expectackseqnum
	if (expectackseqnum > s):
		break
	if (send_base > s):
		continue
	ss.sendto(bfr[send_base],addr)
	print("PKT SEND DAT 512 " + str(send_base))
	send_base = send_base + 1
	window_size = window_size + 1


ss.sendto(bfr[s+1],addr)
print("PKT SEND EOT 12 " + str(send_base))
while (True):
	data,add = ss.recvfrom(512)
	pt = struct.unpack("!I",data[0:4])
	pl = struct.unpack("!I",data[4:8])
	sn = struct.unpack("!I",data[8:12])
	print("PKT RECV EOT 12 " + str(sn[0]))
	if (pt[0] == 2):
		break;
ss.close()

