#!/usr/bin/env python
from socket import *
import sys,os
import struct

if len(sys.argv) != 4 and len(sys.argv) != 6 and len(sys.argv) != 7:
	print("Error Input")
	quit()
host = sys.argv[1]
port = int(sys.argv[2])
opkey = sys.argv[3]

# Initialize.
addr = (host,port)
client = socket(AF_INET, SOCK_STREAM)
try:
	client.connect(addr)
except Exception as e:
	print("Connection failed!")

if opkey[0] == 'F':
	msg = b'F\0\0\0\0\0\0\0\0'
	client.send(msg)
elif opkey[0] == 'G':
	msg = str.encode(opkey)
	client.send(msg)
	file_name = sys.argv[4]
	recv_size = int(sys.argv[5])
	f = open(file_name, 'w+')
	data = client.recv(1024)
	while data:
		f.write(data)
		data = client.recv(recv_size)
	f.close()
elif opkey[0] == 'P':
	msg = str.encode(opkey)
	client.send(msg)
	file_name = sys.argv[4]
	send_size = int(sys.argv[5])
	wait_time = int(sys.argv[6])
	client.settimeout(wait_time/1000)

	# checking for digit input or real file
	if file_name.isdigit():
		size = int(file_name)
		while (size > 0):
			msg = "\0" * send_size
			msg = msg.encode("utf-8")
			client.send(msg)
			size = size - send_size
	else:
		f = open(file_name,'rb')
		message = f.read(send_size)
		while (message):
			client.send(message)
			message = f.read(send_size)
		f.close()
else:
	print("Error Input")

client.close()

